src/Acme.Store.UI.Mvc/Controllers/CategoriasController.cs
using Acme.Store.Business.Interfaces.Repositories;
using Acme.Store.Business.Interfaces.Services;
using Acme.Store.Business.Interfaces;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Acme.Store.Data.Repositories;
using Acme.Store.UI.Mvc.Models;
using Acme.Store.Business.Models;
using Acme.Store.Data.Services;
using Acme.Store.Abstractions.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Acme.Store.Auth.Interfaces;

namespace Acme.Store.UI.Mvc.Controllers
{
    [Authorize]
    [Route("categorias")]
    public class CategoriasController : MainController
    {
        private readonly ICategoriaService _categoriaService;
        private readonly ICategoriaRepository _categoriaRepository;
        private readonly IMapper _mapper;

        public CategoriasController(ICategoriaService categoriaService,
                                    ICategoriaRepository categoriaRepository,
                                    IMapper mapper,
                                    INotificador notificador,
                                    ILogger<MainController> logger,
                                    IAspNetUser aspNetUser) : base(notificador, logger, aspNetUser)
        {
            _categoriaService = categoriaService;
            _categoriaRepository = categoriaRepository;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            var categorias = _mapper.Map<IEnumerable<CategoriaViewModel>>(await _categoriaRepository.ObterTodos())
                                .OrderBy(p => p.Nome);

            return View(categorias);
        }

        [Route("detalhes/{id:guid?}")]
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null || id.Value == Guid.Empty)
            {
                return NotFound();
            }

            var categoria = await _categoriaRepository.ObterPorId(id.Value);
            if (categoria == null)
            {
                return NotFound();
            }

            return View(_mapper.Map<CategoriaViewModel>(categoria));
        }

        [Route("criar-novo")]
        public async Task<ActionResult> Create()
        {
            var categoria = _mapper.Map<CategoriaViewModel>(new Categoria());

            return View(categoria);
        }

        [HttpPost("criar-novo")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind("Id,Nome,Descricao")] CategoriaViewModel categoria)
        {
            if (ModelState.IsValid)
            {
                if (categoria == null)
                {
                    return NotFound();
                }

                await _categoriaService.Adicionar(_mapper.Map<Categoria>(categoria));

                return RedirectOrReturn(nameof(Index), nameof(Create), categoria);

            }
            return View(categoria);
        }

        [Route("editar/{id:guid}")]
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            var categoria = _mapper.Map<CategoriaViewModel>(await _categoriaRepository.ObterPorId(id.Value));
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpPost("editar/{id:guid}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid? id, [Bind("Id,Nome,Descricao")] CategoriaViewModel categoria)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            if (id != categoria.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _categoriaService.Atualizar(_mapper.Map<Categoria>(categoria));

                return RedirectOrReturn(nameof(Index), nameof(Edit), categoria);
            }

            return View(categoria);
        }

        [Route("excluir/{id:guid}")]
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            var categoria = _mapper.Map<CategoriaViewModel>(await _categoriaRepository.ObterPorId(id.Value));
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpPost("excluir/{id:guid}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid? id, [Bind("Id,Nome,Descricao")] CategoriaViewModel categoria)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            await _categoriaService.Remover(id.Value);

            if (! OperacaoValida())
            {
                categoria = _mapper.Map<CategoriaViewModel>(await _categoriaRepository.ObterPorId(id.Value));
                if (categoria == null)
                {
                    return NotFound();
                }
                return View(categoria);
            }

            return Redirect("Index");
        }
    }
}

src/Acme.Store.UI.Mvc/Controllers/ProdutosController.cs
using Acme.Store.Abstractions.Interfaces;
using Acme.Store.Auth.Interfaces;
using Acme.Store.Business.Constants;
using Acme.Store.Business.Interfaces;
using Acme.Store.Business.Interfaces.Repositories;
using Acme.Store.Business.Interfaces.Services;
using Acme.Store.Business.Models;
using Acme.Store.Business.Pagination;
using Acme.Store.UI.Mvc.Models;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace Acme.Store.UI.Mvc.Controllers
{
    [Authorize]
    [Route("produtos")]
    public class ProdutosController : MainController
    {
        private readonly IProdutoService _produtoService;
        private readonly ICategoriaRepository _categoriaRepository;
        private readonly IVendedorRepository _vendedorRepository;
        private readonly IMapper _mapper;

        public ProdutosController(IProdutoService produtoService,
                                  IProdutoRepository produtoRepository,
                                  ICategoriaRepository categoriaRepository,
                                  IVendedorRepository vendedorRepository,
                                  IMapper mapper,
                                  INotificador notificador, 
                                  ILogger<MainController> logger,
                                  IAspNetUser aspNetUser) : base(notificador, logger, aspNetUser)
        {
            _produtoService = produtoService;
            _categoriaRepository = categoriaRepository;
            _vendedorRepository = vendedorRepository;
            _mapper = mapper;
        }

        [AllowAnonymous]
        public async Task<ActionResult> Index()
        {
            var produtos = _mapper.Map<IEnumerable<ProdutoExibirViewModel>>(await _produtoService.ObterTodos())
                                .OrderBy(p => p.Nome);

            return View(produtos);
        }

        [Route("detalhes/{id:guid?}")]
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null || id.Value == Guid.Empty)
            {
                return NotFound();
            }

            var produto = await _produtoService.ObterPorId(id.Value);
            if (produto == null)
            {
                return NotFound();
            }

            if (_aspNetUser.GetUserId() != produto.VendedorId)
            {
                return Unauthorized();
            }

            return View(_mapper.Map<ProdutoExibirViewModel>(produto));
        }

        [Route("criar-novo")]
        public async Task<ActionResult> Create()
        {
            var produtoVM = new ProdutoIncluirViewModel();

            produtoVM.CategoriasSelectList = await ObterCategoriasSelectList(produtoVM.CategoriaId);
            if (_aspNetUser.IsInRole(Roles.Admin))
            {
                produtoVM.VendedoresSelectList = await ObterVendedoresSelectList(produtoVM.VendedorId);
            }

            return View(produtoVM);
        }

        [ValidateAntiForgeryToken]
        [HttpPost("criar-novo")]
        public async Task<IActionResult> Create([Bind("Id,Nome,Descricao,CategoriaId,VendedorId,Preco,QuantidadeEstoque,UnidadeVenda,ImagemUpload")] ProdutoIncluirViewModel produto)
        {
            if (ModelState.IsValid)
            {
                if (produto == null)
                {
                    return NotFound();
                }

                var formFile = produto.ImagemUpload;
                var prod = _mapper.Map<Produto>(produto);

                if (!_aspNetUser.IsInRole(Roles.Admin))
                {
                    var vendedor = await _vendedorRepository.ObterPorEmail(_aspNetUser.GetUserEmail());
                    if (vendedor == null)
                    {
                        NotificarErro("O usuário logado não está cadastrado como vendedor.");
                        return View(produto);
                    }
                    prod.VendedorId = vendedor.Id;
                }

                await _produtoService.Adicionar(_aspNetUser, prod, formFile);

                if (OperacaoValida())
                {
                    return RedirectToAction("Index");
                }
                produto.ImagemUpload = formFile;
            }

            produto.CategoriasSelectList = await ObterCategoriasSelectList(produto.CategoriaId);
            if (_aspNetUser.IsInRole(Roles.Admin))
            {
                produto.VendedoresSelectList = await ObterVendedoresSelectList(produto.VendedorId);
            }

            return View(produto);
        }

        [Route("editar/{id:guid}")]
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            var produto = await _produtoService.ObterPorId(id.Value);
            if (produto == null)
            {
                return NotFound();
            }

            if (_aspNetUser.GetUserId() != produto.VendedorId)
            {
                return Unauthorized();
            }

            var produtoVM = _mapper.Map<ProdutoEditarViewModel>(produto);
            produtoVM.CategoriasSelectList = await ObterCategoriasSelectList(produtoVM.CategoriaId);
            if (_aspNetUser.IsInRole(Roles.Admin))
            {
                produtoVM.VendedoresSelectList = await ObterVendedoresSelectList(produtoVM.VendedorId);
            }

            return View(produtoVM);
        }

        [HttpPost("editar/{id:guid}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Guid? id, [Bind("Id,Nome,Descricao,CategoriaId,VendedorId,Preco,QuantidadeEstoque,UnidadeVenda,ImagemUpload")] ProdutoEditarViewModel produto)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            if (id != produto.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var formFile = produto.ImagemUpload;
                var prod = _mapper.Map<Produto>(produto);

                if (!_aspNetUser.IsInRole(Roles.Admin))
                {
                    var vendedor = await _vendedorRepository.ObterPorEmail(_aspNetUser.GetUserEmail());
                    if (vendedor == null)
                    {
                        NotificarErro("O usuário logado não está cadastrado como vendedor.");
                        return View(produto);
                    }
                    prod.VendedorId = vendedor.Id;
                }

                await _produtoService.Atualizar(_aspNetUser, prod, formFile);

                if (OperacaoValida())
                {
                    return RedirectToAction(nameof(Index));
                }
                produto.ImagemUpload = formFile;
            }

            produto.CategoriasSelectList = await ObterCategoriasSelectList(produto.CategoriaId);
            if (_aspNetUser.IsInRole(Roles.Admin))
            {
                produto.VendedoresSelectList = await ObterVendedoresSelectList(produto.VendedorId);
            }

            return View(produto);
        }

        // GET: ProdutosController/Delete/5
        [Route("excluir/{id:guid}")]
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            var produto = await _produtoService.ObterPorId(id.Value);
            if (produto == null)
            {
                return NotFound();
            }

            if (_aspNetUser.GetUserId() != produto.VendedorId)
            {
                return Unauthorized();
            }

            return View(_mapper.Map<ProdutoExibirViewModel>(produto));
        }

        // POST: ProdutosController/Delete/5
        [HttpPost("excluir/{id:guid}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid? id, [Bind("Id,Nome,Descricao,CategoriaId,VendedorId,Preco,QuantidadeEstoque,UnidadeVenda,ImagemUpload")] ProdutoExibirViewModel produto)
        {
            if (id == null || id == Guid.Empty)
            {
                return NotFound();
            }

            await _produtoService.Remover(_aspNetUser, id.Value);

            if (!OperacaoValida())
            {
                produto = _mapper.Map<ProdutoExibirViewModel>(await _produtoService.ObterPorId(id.Value));
                if (produto == null)
                {
                    return NotFound();
                }
                return View(produto);
            }

            return Redirect("Index");
        }

        private async Task<SelectList> ObterCategoriasSelectList(Guid? selectedId)
        {
            var items = new List<SelectListViewModel>()
            {
                new SelectListViewModel()
                {
                    Id = null,
                    Nome = "Selecione uma categoria..."
                }
            };

            items.AddRange(_mapper.Map<IEnumerable<SelectListViewModel>>((await _categoriaRepository.ObterTodos()).OrderBy(c => c.Nome)));
            return new SelectList(items, "Id", "Nome");
        }

        private async Task<SelectList> ObterVendedoresSelectList(Guid? selectedId)
        {
            var items = new List<SelectListViewModel>() 
            { 
                new SelectListViewModel() 
                {
                    Id = null,
                    Nome = "Selecione um vendedor..."
                }
            };

            items.AddRange(_mapper.Map<IEnumerable<SelectListViewModel>>((await _vendedorRepository.ObterTodos()).OrderBy(c => c.Nome)));
            return new SelectList(items, "Id", "Nome", selectedId);
        }

src/Acme.Store.UI.Mvc/Views/Shared/_FiltroCategoriaPartial - Copy.cshtml
@using Acme.Store.Business.Interfaces.Repositories
@using Acme.Store.Business.Models
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> _signInManager
@inject UserManager<IdentityUser> _userManager
@inject IVendedorRepository _vendedorRepository

<ul class="navbar-nav">
    <li class="nav-item">
        <a class="nav-link text-dark"> Vendedor: </a>
    </li>
    @if (_signInManager.IsSignedIn(User))
    {
        var id = Guid.Parse(_userManager.GetUserId(User));
        var vendedor = await _vendedorRepository.ObterPorId(id);
        var nome = vendedor?.Nome ?? User.Identity?.Name;

        <li class="nav-item">
            <a class ="nav-link text-dark">Olá @nome!</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-gear"></i>
            </a>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">Sua conta</a>
                </li>
                <li class="nav-item">
                    <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button type="submit" class="dropdown-item">Logout</button>
                    </form>
                </li>
            </ul>
        </li>
    }
    else
    {
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Vendedores" asp-action="Create">Registre-se</a>
        </li>
    }
</ul>

src/Acme.Store.UI.Mvc/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> _signInManager
@inject UserManager<IdentityUser> _userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ACME Web Store</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    @* <script type="importmap"></script> *@
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    @* <link rel="stylesheet" href="~/Acme.Store.UI.Mvc.styles.css" asp-append-version="true" /> *@

    @await RenderSectionAsync("Links", required: false)
</head>
<body>
    <div class="container">
    <header>
        <div class="pb-3">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="/img/acme_logo_small.png" alt="ACME" width="auto" height="40">
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                        @if (_signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categorias" asp-action="Index">Categorias</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Vendedores" asp-action="Index">Vendedores</a>
                            </li>
                        }
                    </ul>

                    <partial name="_LoginPartial" />
                </div>
            </nav>
        </div>
    </header>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2025 - ACME Web Store
        </div>
    </footer>
@*
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
 *@
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.min.js"></script>
    </environment>

    <script>
        const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
        const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>